### ISSUE TITLE
bad image url 

### ISSUE THREAD

**Issue by Jimmuy** [wy521angel/MarkdowmPhotos#1]
it seems that this image url can not be reached.
FYI(https://github.com/wy521angel/MarkdowmPhotos/blob/master/IT/%E7%BD%91%E7%BB%9C%E4%B8%8E%E5%8D%8F%E8%AE%AE/HTTPS%E7%9A%84%E8%BF%9E%E6%8E%A5%E5%BB%BA%E2%BD%B4%E8%BF%87%E7%A8%8B%EF%BC%88%E4%B8%8D%E5%AE%8C%E6%95%B4%EF%BC%89.jpg)

**Comment by wy521angel** [comment]
Ok, I see. You can refer to the following method
https://blog.csdn.net/qq_38232598/article/details/91346392
